import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE

def clusterPlot2D(data, generatedCluser):
  ''' The parameters accepted by this function are as follows:
    1. "data" is the dataset used for the clustering and the data type is a NumPy array. (data = tranformed_data)
    2. "generatedCluser" is a 1-column array of the generated cluster by the applied method. (generatedCluser = result)  
    
    Return value:
       The function will reduce the dataset into 2 columns using the T-SNE method and 
       then will plot the clusters in a 2D scatter plot using 2 features generated by T-SNE.  
       -- By Omar Faruque
      '''
  tsne = TSNE(n_components=2, learning_rate='auto', perplexity=10, init='random')
  tsne_data = tsne.fit_transform(data)
  tsne_data
  tsne_df = pd.DataFrame(tsne_data, columns=['Feature-1','Feature-2'])
  tsne_df['cluster'] = pd.Categorical(generatedCluser)
  sns.scatterplot(x="Feature-1",y="Feature-2",hue="cluster",data=tsne_df).set(title='Weather Data Clusters')
  plt.legend(title='Clusters', bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0)
